const MODES = {
    ADMIN: 0,
    LOGGED_IN: 1,
    LOGGING_IN: 2,
    SIGNING_UP: 3,
    PASWORD_RESET_REQUEST: 4,
    PASSWORD_REQUEST_HANDLE: 5,
    LOADING: 6,
    LOGGING_OUT: 7
}

const ADMINMODES = {
    REVIEW_REQUESTS: 0,
    INVITE_USER: 1,
    MANAGE_CLUBS: 5,
    MANAGING_OWN_DETAILS: 6
}

const USERMODES = {
    BOOKING: 0,
    ADDING_RACER: 1,
    MANAGING_DETAILS: 2
}

const COMPLETING_MODES = {
    LOADING: 0,
    INVALID_TOKEN: 1,
    NO_TOKEN: 2,
    TOKEN_FOUND: 3,
    SUBMIT_GOOD: 4,
    SUBMIT_BAD: 5,
}

export {
    ADMINMODES,
    COMPLETING_MODES,
    MODES,
    USERMODES
}